### ISSUE TITLE
타회원의 비공개 문제집에 대한 접근 제어가 필요합니다.

### ISSUE THREAD

**Issue by Begachu** [team-quddy/Quddy-backend#1]
요청 url : `[GET] api/setter/exam/${id}`, `[GET] api/template/${id}`

회원 A가 만든 비공개 문제집에 대해 회원B가 해당 요청으로 열람이 가능합니다.
응답 전 사용자 id에 따른 분기 처리가 필요할 것 같습니다.

**Comment by seunghee114** [comment]
요청 url : `[GET] api/setter/exam/${id}`
해당 요청은 자신의 문제집에 대한 통계 결과이기 때문에 문제집 출제자만 접근 가능하도록 변경했습니다.
요청 url : `[GET] api/template/${id}`
해당 요청은 템플릿에 대한  상세 정보이기 때문에 비공개 문제집인 경우는 접근이 불가능하도록 변경했습니다.
