### ISSUE TITLE
비회원에 대해 시험 응시가 불가능합니다.

### ISSUE THREAD

**Issue by Begachu** [team-quddy/Quddy-backend#11]
요청 url : `api/solver/exam/:id`

해당 요청은 쿠키가 없는 비회원도 요청할 수 있습니다.
현재는 비회원인 경우 400 코드를 반환합니다.

**Comment by seunghee114** [comment]
해당 요청의 경우 (https://github.com/team-quddy/Quddy-backend/issues/10)
미응시자인 경우 시험 정보를 response로 보내고 응시자인 경우 result id를 response로 보내고 있습니다. 그러기 위해서는 쿠키가 필요하다고 판단되는데, 

쿠키가 없는 경우에 미응시자인 경우와 똑같이 시험 정보를 response로 보낸다면 
시험 채점하기 요청에서 에러가 발생할 텐데 이때는 어떻게 처리할 예정인지 궁금합니다~

**Comment by Begachu** [comment]
비회원(쿠키 없는 경우)인 경우 첫 번째 문제 진입 전 로그인 절차를 한 번 거친 후 문제를 응시하게 됩니다.
프론트 측에서 응시 페이지 접근 시 `회원정보 요청`을 통해 회원가입 여부를 판단, 
비회원인 경우 응시 첫페이지에서 사용자로부터 닉네임을 받아 `회원가입 요청`을 보낸 후 다음 페이지로 넘어갈 수 있도록 구현했습니다.

따라서 우려하신 부분인 `시험 채첨하기 요청`을 보낸 시점에서는 반드시 쿠키가 포함되어 있을 예정입니다.

**Comment by seunghee114** [comment]
해당 요청에 대해 다음과 같이 처리했습니다.

미응시자인 경우 or 비회원인 경우
```
{
    exam: {
        title: string,
        problems: [
            {
                id: string,
                question: string,
                exImg: string,
                exText: string,
                isObjective: boolean,
                opt: string
            }, ...
        ]
    },
}
```
응시자인 경우
```
{
    id: string
 }
```
