### ISSUE TITLE
쿠키가 없는 경우 공개된 템플릿의 상세 정보 조회가 불가능합니다.

### ISSUE THREAD

**Issue by Begachu** [team-quddy/Quddy-backend#5]
요청 url : [GET] /api/template/:id

비회원인 상태에서 공개된 템플릿에 대한 상세 정보 요청을 보내면 아래와 같이 응답합니다:
```
{
    "timestamp": "2023-10-14T15:17:37.867+00:00",
    "status": 400,
    "error": "Bad Request",
    "path": "/api/template/1"
}
```

공개된 템플릿의 경우 비회원 상태에서도 상세 정보 조회가 가능해야하기 때문에 수정이 필요해보입니다.
또한 요청 실패에 대한 상태코드나 메시지를 상세히 작성해주시면 더욱 좋을 것 같습니다!

**Comment by seunghee114** [comment]
수정했습니당
