### ISSUE TITLE
시험 문제 가져오기 요청을 만들어주세요.

### ISSUE THREAD

**Issue by Begachu** [team-quddy/Quddy-backend#6]
요청 url :  `[GET] /api/solver/exam/:id`

응시자 화면을 위해 위의 요청이 필요합니다.
원하는 응답은 아래와 같습니다.

```
{
    id: string || null,       // 응시한 경우 응시결과 id를 , 미응시한 경우 Null
    exam: {
        title: string,
        problems: [
            {
                id: string,
                question: string,
                exImg: string,
                exText: string,
                isObjective: boolean,
                opt: string
            }, ...
        ]
    },
}
```

**Comment by Begachu** [comment]
응시 결과 id의 경우는 두 가지 방법이 있을 것 같습니다.

1. db 테이블 추가
2. examid를 기반으로 userid 암호화하여 제공

**Comment by seunghee114** [comment]
2번 방법으로 진행할 것 같습니다.
응시한 경우에는 응시결과 ID만 주면 되나요? 따로 응시 결과 가져오기 요청을 보내는 건지 궁금합니다~

**Comment by Begachu** [comment]
네 응시한 경우는 아래처럼 주시면 좋을 것 같습니다.
id가 있는 경우, id를 사용하여 프론트 측에서 페이지 이동 후 응시 결과 가져오기 요청을 보냅니다.

```
{
    id: string
}
```

**Comment by seunghee114** [comment]
요청 url : `[GET] /api/solver/exam/:id` 로 만들었습니당
