### ISSUE TITLE
시험 문제 결과 가져오기 요청을 만들어주세요.

### ISSUE THREAD

**Issue by Begachu** [team-quddy/Quddy-backend#7]
요청 url : `[GET] /api/solver/result/:id`

시험 문제 결과에 대한 정보를 제공하는 요청이 필요합니다.
해당 요청의 경우 회원 비회원 여부와 상관없이 반환하도록 만들어주시면 감사하겠습니다.

원하는 응답 결과는 다음과 같습니다.
```
{
    exam: {
        title: string,
        problems: [
            {
                id: string,
                question: string,
                exImg: string,
                exText: string,
                isObjective: boolean,
                opt: string,
                answer: string,    // 문제 정답 정보
                submitAnswer: string    // 사용자가 보낸 응답
            }, ...
        ]
    },
    result : {
        problemCnt: number,    // 전체 문제 수
        correct: number,            // 맞춘 문제 수
        percentile: number,       // 응시자의 등수/전체 응시자 수
        firstSolver: boolean,      // 첫번째 응시자인지 여부
    }   
}
```

**Comment by Begachu** [comment]
[응시결과 id에 대하여](https://github.com/team-quddy/Quddy-backend/issues/6#issuecomment-1763037620)
위의 선택지 중 2번을 선택한 경우 해당 요청의 url을 아래와 같이 수정하면 좋을 것 같습니다.

요청 url : `[GET] /api/solver/exam/:examid/:resultid`

**Comment by seunghee114** [comment]
응시 결과 id를 구성할 때 2번 방법을 선택했고, 
exam id와 users id를 기반으로 암호화하기 때문에 요청 url을 아래와 같이 수정할 수 있을 것 같습니다. 

요청 url : `[GET] /api/solver/:resultid`

**Comment by Begachu** [comment]
examid가 없는데 위의 요청으로 examid와 userid를 확보할 수 있나요?
현재 어떤 로직으로 암호화 방식이 구현되어 있는지 몰라 여쭤봅니다.
해당 요청에는 쿠키가 없을 수 있습니다. 응시자 본인이 아닌 유저도 같은 결과를 볼 수 있어야합니다.

2번째 방법 사용 시 `[GET] /api/solver/exam/:examid/:resultid` url을 제안한 이유는 다음과 같습니다.
- 모든 응시 결과를 조회하기 위해서는 현재 `userid`와 `examid`가 필요함
- `resultid`는 두 id의 조합으로 이를 통해 `userid`와 `examid`를 알아낼 수 있어야 함
- 별도의 테이블을 사용하지 않는 경우, `resultid` 하나로 `userid`와 `examid`를 알아낼 수 있는가?
- 응시 결과를 링크로 공유하는 경우에는 사실 상 `examid`가 공개되어있다고(적어도 공유하는 사람끼리는) 볼 수 있다고 판단, 굳이 암호화가 필요없음
- `userid`의 경우 절대적으로 암호화가 필요, `examid`와 추가 key를 조합하여 `userid`를 암호화 -> 이것을 `resultid`라 가정
- 요청 시 `examid`와 `resultid`를 받으면, 이를 조합하여 backend 측에서 이 둘을 통해 `userid` 또한 확보 가능

혹시 현재 백엔드 측에서 resultid를 어떤 식으로 암호화하고 복호화하는지 알 수 있을까요?

**Comment by seunghee114** [comment]
요청 url : `[GET] /api/solver/result/:resultid`  로 만들었습니당~
