### ISSUE TITLE
시험 채점 요청을 수정해주세요.

### ISSUE THREAD

**Issue by Begachu** [team-quddy/Quddy-backend#8]
요청 url : `[POST] /solver/exam/:id`

현재 노션 api 명세된 시험 채점 요청에 수정이 필요할 것 같아 이슈 남깁니다.

examid(=id)의 경우 body와 path variable에 중복으로 들어가 있습니다.
때문에 request를 아래와 같이 수정하거나 url을 수정하면 좋을 것 같습니다.
```
// request data
{
    problems: [
        {
            id: string,          // 문제 id
            answer: string  // 응시자 응답
        },
        ...
    ]
}
```
or 
`[POST] /solver/exam`

-----

요청의 response의 경우 결과 페이지로 이동을 위해 resultid(응시결과 id)를 받환받고자 합니다.
```
// response data
{
    id : string         // 응시결과 id
}
```

**Comment by seunghee114** [comment]
`[POST] /solver/exam` 으로 변경하였습니다.

해당 요청의 response를 맞은 개수에서 resultId로 변경하였습니다.
